apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ssfi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ssfi
    app.kubernetes.io/part-of: ci10t-776-0026-app
  name: devfile-sample-ssfi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ssfi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ssfi
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0026-tenant/ci10t-776-0026-app/devfile-sample-ssfi@sha256:1ee47501b19ffb7586b0e1c62b3c7cccec9d48e4be757492e74cd5e4c7a0973a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
