apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ssfi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0026-tenant/ci10t-776-0026-app/devfile-sample-ssfi@sha256:1ee47501b19ffb7586b0e1c62b3c7cccec9d48e4be757492e74cd5e4c7a0973a
        name: my-nodejs
        resources: {}
status: {}
